# Generated by Django 5.1.2 on 2025-01-04 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('complete', 'Complete'), ('yearly', 'Yearly'), ('monthly', 'Monthly')], max_length=100)),
                ('plan', models.CharField(choices=[('one year', 'One'), ('four years', 'Four'), ('eight years', 'Eight')], max_length=100)),
                ('status', models.CharField(choices=[('checking', 'Checking'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='checking', max_length=100)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('accepted_date', models.DateField(default='')),
                ('expired_date', models.DateField(default='')),
                ('time_left', models.TimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('expert', 'Expert')], default='user', max_length=100)),
            ],
        ),
    ]
