# Generated by Django 5.1.2 on 2025-01-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='time_left',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='payment_method',
            field=models.CharField(choices=[('complete', 'Complete'), ('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=100),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='plan',
            field=models.CharField(choices=[('one year', 'One'), ('four years', 'Four'), ('eight years', 'Eight')], default='one year', max_length=100),
        ),
    ]
