# Generated by Django 5.1.2 on 2025-01-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insurance_time_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.user'),
        ),
    ]
