# Generated by Django 5.1.2 on 2025-01-04 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insurance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='expired_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
