# Generated by Django 5.1.2 on 2025-01-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_insurance_expired_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='user_name',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('national_id', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('job_title', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('marriage', models.CharField(max_length=100)),
                ('job_address', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.user')),
            ],
        ),
    ]
